services:
  app:
    build: .
    volumes:
      - .:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./odoo-data:/var/lib/odoo
    env_file:
      - .env

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

# Tambahkan blok ini di baris paling bawah
networks:
  default:
    name: database-server_default
    external: true