# -*- coding: utf-8 -*-

# 1: imports of python lib
from datetime import date, datetime, timedelta,time
from dateutil.relativedelta import relativedelta

# 2: import of known third party lib

# 3:  imports of odoo
from odoo import models, fields, api, _
from odoo.exceptions import ValidationError

# 4:  imports from odoo modules

# 5: local imports

# 6: Import of unknown third party lib
class WIPWorkOrder(models.Model):
    _name = "tw.work.order.wip"
    _description = "TW Work Order WIP"

    # 7: defaults methods
    def _get_default_branch(self):
        company_ids = False
        company_ids = self.env.companies
        if company_ids and len(company_ids) == 1 :
            return company_ids[0].id
        return False

    @api.model
    def _get_default_date(self):
        return date.today()

    @api.model
    def _get_default_datetime(self):
        return datetime.now()

    # 8: fields
    name = fields.Char('Name', compute='_compute_name', store=True)
    date = fields.Date('Date',default=_get_default_date)
    qty_wip = fields.Integer('Qty WIP',compute="_compute_detail_wip",readonly=True)
    generate_date = fields.Datetime('Generated on')
    confirm_date = fields.Datetime('Confirmed on')
    state = fields.Selection([
        ('draft','Draft'),
        ('done','Done')],default='draft')

    # 9: relation fields
    company_id = fields.Many2one('res.company','Branch',default=_get_default_branch)
    detail_ids = fields.One2many('tw.work.order.wip.line','wip_id','Details')
    other_ids = fields.One2many('tw.work.order.wip.other','wip_id','Others')
    generate_uid = fields.Many2one('res.users','Generated by')
    confirm_uid = fields.Many2one('res.users','Confirmed by')

    # 10: constraints & sql constraints

    # 11: compute/depends & on change methods
    @api.depends('detail_ids','other_ids')
    def _compute_detail_wip(self):
        for me in self:
            total = len(me.detail_ids) + len(me.other_ids)
            me.qty_wip = total

    @api.depends('company_id')
    def _compute_name(self):
        for record in self:
            seq_name = self.env['ir.sequence'].with_company(record.company_id).get_sequence_code('WIP', record.company_id.code)
            record.name = seq_name

    # 12: override methods
        
    def action_get_wip(self):
        where = " WHERE wo.state in ('waiting_for_approval','confirmed','approved','finished')"
        if self.company_id:
            where += " AND wo.company_id = %d" %(self.company_id.id)
        query = """
            SELECT wo.id as wo_id
                , wo.date as tgl_wo
                , (current_date - wo.date) as aging
                , wo.plate_number as plate_number
                , wo.state as state_wo
                , wo.state_wo AS status_wo
                , CASE WHEN ws.value = 'REG' THEN 'Regular'
                WHEN ws.value = 'WAR' THEN 'Job Return'
                WHEN ws.value = 'CLA' THEN 'Claim'
                WHEN ws.value = 'SLS' THEN 'Part Sales' END as type_wo
            FROM tw_work_order wo
            LEFT JOIN tw_selection ws ON ws.id = wo.type_id
            %s
        """ %(where)
        self._cr.execute(query)
        ress = self._cr.dictfetchall()
        if not ress:
            raise ValidationError(_('Data WIP tidak ditemukan !'))
        detail_ids = []
        for res in ress:
            detail_ids.append([0,False,{
                'wo_id':res.get('wo_id'),
                'tgl_wo':res.get('tgl_wo'),
                'aging':res.get('aging'),
                'plate_number':res.get('plate_number'),
                'state_wo':res.get('state_wo').replace('_',' ').title() if res.get('state_wo') else '',
                'status_wo':res.get('status_wo').replace('_',' ').title() if res.get('status_wo') else '',
                'type_wo':res.get('type_wo'),
            }])
        self.write({
            'generate_date':self._get_default_datetime(),
            'generate_uid':self._uid,
            'detail_ids':detail_ids
        })


    def action_confirm(self):
        self.write({
            'state':'done',
            'confirm_uid':self._uid,
            'confirm_date':self._get_default_datetime(),      
        })

    def action_back_to_draft(self):
        for line in self.detail_ids:
            line.validation_status = 'draft'
        for other in self.other_ids:
            other.validation_status = 'draft'
        self.write({
            'state':'draft',
        })

    def unlink(self):
        for me in self:
            if me.state != 'draft':
                raise ValidationError(_('Tidak bisa dihapus WIP selain Draft !'))
        return super(WIPWorkOrder, self).unlink()
    
    def _check_validasi(self):
        for line in self.detail_ids:
            line.validation_status = 'done'
        for other in self.other_ids:
            other.validation_status = 'done'