from . import tw_purchase_return
from . import tw_purchase_return_line
from . import tw_account_move_line_inherit
from . import tw_account_move_inherit
from . import tw_stock_inherit
from . import tw_account_setting_inherit
from . import tw_stock_warehouse_inherit
from . import tw_stock_line_inherit
from . import tw_stock_picking_inherit
from . import tw_stock_rule_inherit
from . import tw_procurement_group_inherit
