import base64
import io
from odoo import models, fields, api
from odoo.exceptions import UserError as Warning
from datetime import datetime
import json
import string
import random
from PIL import Image, ImageDraw, ImageFont
from odoo.tools.misc import file_path as file_path_util

class StockOpname(models.Model):
    _name = "tw.stock.opname"
    _order = "id DESC"
    _description = "Stock Opname"

    def _get_default_main_dealer_code(self):
        return self.env['res.company'].get_default_main_dealer_code()

    def _get_default_datetime(self):
        return datetime.now()
    
    def _get_default_branch(self):
        company_ids = False
        company_ids = self.env.companies
        if company_ids and len(company_ids) == 1 :
            return company_ids[0].id
        return False

    name = fields.Char('Name', index='trigram', compute='_compute_name', store=True)
    date = fields.Date(string='Date',default=_get_default_datetime)
    periode_awal = fields.Datetime(string='Periode Awal')
    periode_akhir = fields.Datetime(string='Periode Akhir')
    total_data = fields.Integer(string='Total Data', compute='_compute_summary_data', store=True)
    counted = fields.Integer(string='Counted', compute='_compute_summary_data', store=True)
    anomali = fields.Integer(string='Anomali', compute='_compute_summary_data', store=True)
    not_counted = fields.Integer(string='Not Counted', compute='_compute_summary_data', store=True)
    counted_percentage = fields.Integer(string='', compute='_compute_summary_data', store=True)
    anomali_percentage = fields.Integer(string='', compute='_compute_summary_data', store=True)
    not_counted_percentage = fields.Integer(string='', compute='_compute_summary_data', store=True)
    alasan_reject = fields.Text(string='Alasan Reject')
    code = fields.Char('Kode Unik')

    open_uid = fields.Many2one('res.users', string='Generated by')
    open_date = fields.Datetime('Generated on')
    confirm_uid = fields.Many2one('res.users', string='Confirm by')
    confirm_date = fields.Datetime('Confirm on')
    recount_uid = fields.Many2one('res.users', string='Recount by')
    recount_date = fields.Datetime('Recount on')
    force_done_uid = fields.Many2one('res.users', string='Force Done by')
    force_done_date = fields.Datetime('Force Done on')
    done_uid = fields.Many2one('res.users', string='Done by')
    done_date = fields.Datetime('Done on')

    state = fields.Selection([
        ('draft', 'Draft'),
        ('open', 'Open'),
        ('in_progress', 'In Progress'),
        ('recount', 'Recount'),
        ('force_done', 'Force Done'),
        ('done', 'Done'),
    ], string='Status', default='draft')
    
    type_so = fields.Selection([
        ('cycle_count', 'Cycle Count'),
        ('stock_opname', 'Stock Opname') 
    ], string='Tipe')

    division = fields.Selection(selection=lambda self: self.env['tw.selection'].get_division_options())

    # Relation Fields
    employee_id = fields.Many2one('hr.employee', string='Penanggung Jawab',domain="[('company_id','=',company_id)]")
    company_id = fields.Many2one(comodel_name='res.company', string='Branch', default=_get_default_branch, domain=[('parent_id','!=',False)])
    pdi_id = fields.Many2one(comodel_name='hr.employee', string='PDI', domain="[('company_id', '=', company_id)]")
    adh_id = fields.Many2one(comodel_name='hr.employee', string='ADH', domain="[('job_id.name', 'in', ('ADMINISTRATION HEAD','ADMINISTRATION HEAD MD')), ('company_id', '=', company_id)]")
    soh_id = fields.Many2one(comodel_name='hr.employee', string='SOH', domain="[('job_id.name', 'in', ('SALES OPERATION HEAD',)), ('company_id', '=', company_id)]")
    detail_opname_ids = fields.One2many('tw.stock.opname.detail','opname_id')
    detail_accessories_ids = fields.One2many('tw.stock.opname.accessories', 'opname_id')
    partial_opname_ids = fields.One2many('tw.stock.opname.partial','opname_id')
    selisih_opname_ids = fields.One2many('tw.stock.opname.detail','opname_id', domain=[('state','in',('selisih','anomali')), ('reason', '!=', False)])
    open_opname_ids = fields.One2many('tw.stock.opname.detail', 'opname_id', domain=[('state','=','open')])
    open_accessories_opname_ids = fields.One2many('tw.stock.opname.accessories', 'opname_id', domain=[('state','=','open')])
    so_location_ids = fields.One2many('tw.stock.opname.location','opname_id')
    so_accessories_location_ids = fields.One2many('tw.stock.opname.accessories.location','opname_id')
    selisih_accessories_ids = fields.One2many('tw.stock.opname.accessories','opname_id', domain=['|',('state','in',('selisih','anomali')), ('reason', '!=', False)])

    @api.depends('detail_opname_ids.state')
    def _compute_summary_data(self):
        total_data = len(self.detail_opname_ids)
        counted = 0
        not_counted = 0
        anomali = 0
        percentage_counted = 0
        percentage_not_counted = 0
        percentage_anomali = 0
        for record in self.detail_opname_ids:
            if record:
                if record.state == 'open' :
                    not_counted +=1
                if record.state == 'anomali':
                    anomali +=1
                if record.state in ('done', 'selisih'):
                    counted +=1
        
        self.total_data = total_data
        self.counted = counted
        self.not_counted = not_counted
        self.anomali = anomali
        
        if total_data > 0:
            percentage_counted = round((counted / total_data) * 100, 2)
            percentage_not_counted = round((not_counted/total_data) * 100, 2)
            percentage_anomali = round((anomali / total_data) * 100, 2)

        self.counted_percentage = percentage_counted
        self.not_counted_percentage = percentage_not_counted
        self.anomali_percentage = percentage_anomali
    
    @api.depends('company_id')
    def _compute_name(self):
        for record in self:
            record.name = False
            if record.id:
                code = record.company_id.code or 'E'
                prefix = 'SO'
                record.name = record.env['ir.sequence'].suspend_security().get_sequence_code(prefix,code)

    @api.onchange('company_id')
    def _onchange_company_id(self):
        self.employee_id = False
        self.pdi_id = False
        self.adh_id = False
        self.soh_id = False

    @api.constrains('periode_awal','periode_akhir')
    def _check_periode(self):
        for record in self:
            if record.periode_awal and record.periode_akhir:
                if record.periode_akhir < record.periode_awal:
                    raise Warning('Perhatian!\nPeriode akhir tidak boleh kurang dari periode awal.')

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            outstanding_so = self.search([
                ('company_id','=',vals['company_id']),
                ('state','!=','done'),
                ('division','=',vals['division'])
            ])
            if outstanding_so:
                raise Warning('Perhatian!\nAda stock opname yang belum selesai.')
        return super(StockOpname, self).create(vals_list)
        
    def write(self,vals):
        write =  super(StockOpname,self).write(vals)
        return write   
    
    def unlink(self):
        for record in self:
            if record.state != 'draft':
                raise Warning('Perhatian!\nData tidak bisa dihapus.')
        return super(StockOpname, self).unlink()

    def action_recount(self):
        data_list = self.get_data_recount()
        
        if not data_list:
            raise Warning("Tidak Dapat Melakukan Recount, Part Sudah berstatus Done/Open.")

        form_id = self.env.ref('tw_stock_opname.view_tw_stock_opname_partial_wizard').id
        return {
            'type': 'ir.actions.act_window',
            'name': ('Stock Opname Partial'),
            'res_model': 'tw.stock.opname.partial',
            'view_type': 'form',
            'view_mode': 'form',
            'views': [(form_id, 'form')],
            'target':'new',
            'context' : {
                'default_opname_id': self.id,
                'default_partial_line_ids': data_list,
                'default_proses': 'recount',
                'default_division': self.division
            }
        }
    
    def action_done(self):
        self._check_line()
        if not getattr(self, 'approval_ids', None):
            if self.division == 'Unit' and self.open_opname_ids:
                return self.action_open_wizard(self.open_opname_ids)
            elif self.division == 'Extras' and self.open_accessories_opname_ids:
                return self.action_open_wizard(self.open_accessories_opname_ids)
        
        for line in self.detail_opname_ids:
            if line.state == 'open':
                if line.qty_system == 0:
                    line.write({
                            'state':'done'
                            })
                else:
                    raise Warning("Masih Terdapat data unit yang belum dihitung pada lokasi %s\n" %(line.location_id.name))

        for line in self.detail_accessories_ids:
            if line.state == 'open':
                if line.qty_system == 0:
                    line.write({
                        'state': 'done'
                    })
                else:
                    raise Warning("Masih Terdapat data accessories yang belum dihitung pada lokasi %s\n" % (line.location_id.name))

        self.write({
            'state': 'done',
            'done_uid': self._uid,
            'done_date': self._get_default_datetime(),
        })

    def action_open_wizard(self, open_opname_ids):
        if open_opname_ids:
            form_id = self.env.ref('tw_stock_opname.view_force_done_wizard').id
            return {
                'type': 'ir.actions.act_window',
                'name': 'Confirm Force Done',
                'view_type': 'form',
                'view_mode': 'form',
                'res_model': 'tw.stock.opname',
                'views': [(form_id, 'form')],
                'res_id':self.id,
                'target':'new',
            }

    def action_force_done(self):
        self._check_line()
        for opname in self.open_opname_ids:
            if not opname.reason:
                raise Warning("Please provide a reason for all unit before proceeding with RFA.")

        for opname in self.open_accessories_opname_ids:
            if not opname.reason:
                raise Warning("Please provide a reason for all accessories before proceeding with RFA.")

        for opname in self.open_opname_ids:
            opname.suspend_security().write({
                'state':'selisih',
            })

        for opname in self.open_accessories_opname_ids:
            opname.suspend_security().write({
                'state': 'selisih',
            })

        self.write({
            'state': 'done',
            'force_done_uid': self._uid,
            'force_done_date': self._get_default_datetime(),
        })

    def action_baso(self):
        # return self.env.ref('tw_stock_opname.action_tw_stock_opname_baso_wizard').sudo().report_action(self.id)
        form_id = self.env.ref('tw_stock_opname.view_tw_stock_opname_baso_wizard').id
        return {
            'type': 'ir.actions.act_window',
            'name': 'Berita Acara SO Unit',
            'view_type': 'form',
            'view_mode': 'form',
            'res_model': 'tw.stock.opname.baso.wizard',
            'context':{
                'default_opname_id': self.id,
                'default_division': self.division
                },
            'views': [(form_id, 'form')],
            'target': 'new'
        }
        
    def action_input_pic(self):
        if not self.detail_opname_ids:
            raise Warning("Detail Stock Opname Belum Tergenerate, Sehingga Tidak Dapat Input PIC !")

        lokasi_list = []
        for lokasi in self.detail_opname_ids.location_id:
            lokasi_list.append([0, 0, {
                'location_id': lokasi.id,
                'line_type': 'unit',
            }])

        accessories_lokasi_list = []
        for lokasi in self.detail_accessories_ids.location_id:
            accessories_lokasi_list.append([0, 0, {
                'location_id': lokasi.id,
                'line_type': 'accessory',
            }])
        
        form_id = self.env.ref('tw_stock_opname.view_tw_stock_opname_pic_wizard').id
        return {
            'type': 'ir.actions.act_window',
            'name': ('Input PIC Stock Opname'),
            'res_model': 'tw.stock.opname.pic',
            'view_type': 'form',
            'view_mode': 'form',
            'views': [(form_id, 'form')],
            'target':'new',
            'context' : {
                'default_opname_id': self.id,
                'default_so_unit_pic_ids': lokasi_list,
                'default_so_accessories_pic_ids': accessories_lokasi_list,
                'default_division': self.division,
                'default_type_so': self.type_so
            }
        }
    
    def action_partial(self):
        detail_data = self.get_stock_location()
        accessories_data = self.get_accessories_stock_location()
        
        if self.division == 'Unit':
            if not detail_data and not accessories_data:
                raise Warning(f"Data Stock Pada Branch {self.company_id.name} Kosong")
        elif self.division == 'Sparepart':
            if not detail_data:
                raise Warning(f"Data Stock Sparepart Pada Branch {self.company_id.name} Kosong")
        
        partial_line_ids = []
        for line in detail_data:
            partial_line_ids.append([0, 0, {
                'location_id': line['location_id'],
                'qty': line['qty'],
                'line_type': 'unit'
            }])

        partial_accessories_line_ids = []
        for line in accessories_data:
            partial_accessories_line_ids.append([0, 0, {
                'location_id': line['location_id'],
                'qty': line['qty'],
                'line_type': 'accessory'
            }])
            
        form_id = self.env.ref('tw_stock_opname.view_tw_stock_opname_partial_wizard').id

        return {
            'type': 'ir.actions.act_window',
            'name': ('Stock Opname Partial'),
            'res_model': 'tw.stock.opname.partial',
            'view_type': 'form',
            'view_mode': 'form',
            'views': [(form_id, 'form')],
            'target':'new',
            'context' : {
                'default_opname_id': self.id,
                'default_partial_line_ids': partial_line_ids,
                'default_partial_accessories_line_ids': partial_accessories_line_ids,
                'default_proses': 'generate',
                'default_division': self.division
            }
        }

    def action_print_unit_validation(self):
        self.ensure_one()
        return self.env.ref('tw_stock_opname.action_report_tw_stock_opname_unit_validation').report_action(self.id)

    def get_data_recount(self):
        data_list = []
        for line in self.detail_opname_ids:
            if line.state == 'selisih' and line.location_id.id not in data_list:
                data_list.append([0, 0, { 'location_id': line.location_id.id }])
        return data_list
    
    def get_stock_location(self):
        query = f"""
            SELECT sl.id as location_id
                , SUM(sq.quantity) as qty
            FROM stock_quant sq
            INNER JOIN product_product prod ON sq.product_id = prod.id
            LEFT JOIN product_template pt ON prod.product_tmpl_id = pt.id
            LEFT JOIN stock_location sl on sq.location_id = sl.id
            WHERE sq.quantity > 0
            AND sl.active is true
            AND prod.division = '{self.division}'
            AND sl.company_id = {self.company_id.id}
            AND (sl.usage = 'internal' OR sl.usage = 'transit' OR sl.usage = 'nrfs')
            GROUP BY sl.id
        """
        self.env.cr.execute(query)
        return self.env.cr.dictfetchall()
    
    def get_accessories_stock_location(self):
        query = f"""
            SELECT sl.id as location_id
                , SUM(sq.quantity) as qty
            FROM stock_quant sq
            INNER JOIN product_product prod ON sq.product_id = prod.id
            LEFT JOIN product_template pt ON prod.product_tmpl_id = pt.id
            LEFT JOIN stock_location sl on sq.location_id = sl.id
            WHERE sq.quantity > 0
            AND sl.active is true
            AND prod.division = 'Extras'
            AND sl.company_id = {self.company_id.id}
            AND (sl.usage = 'internal' OR sl.usage = 'transit' OR sl.usage = 'nrfs')
            GROUP BY sl.id
        """
        self.env.cr.execute(query)
        return self.env.cr.dictfetchall()
    
    def generate_random_code(self, size=6, chars=string.ascii_uppercase + string.digits):
         return ''.join(random.choice(chars) for _ in range(size))

    def button_download_detail (self):
        opname_id = self.id
        return self.env['tw.stock.opname.download'].sudo().create({'name':'report'}).action_download_detail(opname_id, self.division)

    def button_download_selisih (self):
        opname_id = self.id
        return self.env['tw.stock.opname.download'].sudo().create({'name':'report'}).action_download_detail(opname_id, self.division, 'open')
    
    def button_upload_detail(self):
        pic_list = []
        for line in self.detail_opname_ids:
            if not line.employee_id:
                pic_list.append(str(line.employee_id))

        if pic_list:
            form_id = self.env.ref('tw_stock_opname.view_tw_stock_opname_upload_wizard').id
            return {
                'type': 'ir.actions.act_window',
                'name': ('Upload Stock Opname'),
                'res_model': 'tw.stock.opname.upload',
                'view_type': 'form',
                'view_mode': 'form',
                'views': [(form_id, 'form')],
                'target':'new',
                'context' : {
                    'default_opname_id': self.id
                }
            }
        else:
            raise Warning("Tidak dapat Update PIC, PIC sudah terisi !")
        
    def reject(self):
        self.write({ 
            'reject_uid':self._uid,
            'reject_date':self._get_default_datetime(),
            'state': 'in_progress',
            'alasan_reject': self.alasan_reject,
        })

    def _generate_watermark(self, foto_all_stock_binary, text):

        # 1. Decode base64 ke bytes
        image_bytes = base64.b64decode(foto_all_stock_binary)

        # 2. Buka gambar dari bytes
        image = Image.open(io.BytesIO(image_bytes)).convert("RGBA")

        # 2. Buat layer transparan untuk watermark
        txt_layer = Image.new('RGBA', image.size, (255, 255, 255, 0))
        draw = ImageDraw.Draw(txt_layer)

        # 3. Pilih font
        font_path = file_path_util('tw_stock_opname/static/src/font/Inter.ttf')

        # 4. Tentukan teks dan ukurannya
        image_width, image_height = image.size
        font_size = max(10, int(image_height * 0.03))
        font = ImageFont.truetype(font_path, font_size)

        # 5. Pisah teks jadi kata dan bungkus ke baris
        words = text.split()
        lines = []
        current_line = ""

        for word in words:
            test_line = current_line + " " + word if current_line else word
            test_width = draw.textlength(test_line, font=font)
            if test_width <= image_width - 2 * 10:  # padding kiri-kanan
                current_line = test_line
            else:
                lines.append(current_line)
                current_line = word
        if current_line:
            lines.append(current_line)
        
        # 6. Hitung total tinggi teks (termasuk spasi antar baris)
        line_spacing = 5
        total_text_height = sum([
            font.getbbox(line)[3] - font.getbbox(line)[1] + line_spacing
            for line in lines
        ]) - line_spacing

        # 5. Hitung ukuran teks pakai textbbox
        padding = 10
        text_position = (padding, padding)
        background_height = total_text_height
        background_width = image_width - 2 * padding

        # 6. Gambar background transparan hitam di belakang teks
        rect_position = (
            text_position[0] - 5,                          # kiri
            text_position[1] - 5,                          # atas
            text_position[0] + background_width + 5,       # kanan
            text_position[1] + background_height + 5       # bawah
        )
        draw.rectangle(rect_position, fill=(0, 0, 0, 128))  # hitam transparan

        # 7. Gambar teks warna putih
        y = text_position[1]
        for line in lines:
            draw.text((text_position[0], y), line, font=font, fill=(255, 255, 255, 255))  # putih solid
            y += font.getbbox(line)[3] - font.getbbox(line)[1] + line_spacing

        # 8. Gabungkan gambar asli dan watermark
        watermarked = Image.alpha_composite(image, txt_layer)

        # 9. Simpan dan encode ke base64
        buffer = io.BytesIO()
        watermarked.convert("RGB").save(buffer, format="JPEG")
        buffer.seek(0)
        result_base64 = base64.b64encode(buffer.read()).decode('utf-8')

        # Output: base64_string berisi gambar dengan watermark
        return result_base64

    def _check_line(self):
        if not self.detail_opname_ids:
            raise Warning('Tidak ada detail stock opname !')