{
    "name": "TW Incentive",
    "version": "18.0.1.0.0",
    "depends": [
        "base",
        "hr",
        "tw_branch",
        "tw_branch_setting",
        "tw_selection",
        "tw_product_series",
        "tw_menu",
        "tw_sequence",
        "tw_hr",
        "tw_config_files",
        "tw_dealer_sale_order",
        "tw_firebase",
        "tw_approval",
        "tw_format_upload",
        "web_report",
    ],
    "author": "Tunas Honda",
    "license": "LGPL-3",
    "category": "TW HR / TW HR",
    "website": "https://www.honda-ku.com",
    "summary": "Manage and automate incentive calculations for salesmen.",
    "description": """
        This module provides features to manage, calculate, and track incentives for salesmen.
        It supports incentive rules, approval workflows, historical tracking, and reporting to streamline the incentive process and ensure transparency and accuracy for both management and sales staff.
    """,
    "category": "TW Sales",
    "version": "0.1",
    "license": "AGPL-3",
    "data": [
        "data/data.xml",
        "data/scheduled_actions.xml",
        "data/tw_incentive_firebase_template_data.xml",
        
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        # "security/res_groups_button.xml",
        "security/tw_employee_incentive_group.xml",
        "security/tw_recalculate_incentive_group.xml",
        "security/tw_master_incentive_group.xml",
        "security/tw_master_target_margin_group.xml",
        
        "views/tw_hr_job_inherited.xml",
        'views/tw_dealer_sale_order_inherit_view.xml',
        "views/tw_employee_incentive_view.xml",
        "views/tw_employee_incentive_history_view.xml",
        "views/tw_master_incentive_view.xml",
        "views/tw_master_target_margin_view.xml",
        "views/tw_recalculate_incentive_view.xml",
        "views/tw_master_target_margin_line_view.xml",
        "views/tw_branch_setting_inherit_view.xml",
        
        "wizards/tw_upload_master_incentive_wizard.xml",
        "wizards/tw_upload_master_margin_wizard.xml",
        "wizards/tw_upload_minimum_wage_wizard.xml",
        # "views/tw_res_branch_inherited_view.xml",
        # "views/tw_team_leader_view.xml",
        
        "reports/tw_report_incentive_view.xml",
        "reports/tw_report_sisa_margin_dso_view.xml",
        "reports/tw_report_team_leader_view.xml",
        "views/tw_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
}
