from . import tw_part_hotline
from . import tw_part_hotline_detail
from . import tw_part_hotline_available
from . import tw_part_hotline_alocation_dp
from . import tw_purchase_order_inherit
from . import tw_purchase_order_line_inherit
from . import tw_work_order_inherit
from . import tw_work_order_line_inherit
from . import tw_part_sales_inherit
from . import tw_part_sales_line_inherit
from . import tw_stock_picking_inherit
from . import tw_stock_rule_inherit
from . import tw_branch_setting_inherit
from . import tw_stock_warehouse_inherit